name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn
      - run: yarn test

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: yarn
      - run: yarn compile

      - name: Set alert values
        run: |
          export ALIAS=create-alert-int-test-$(date +%s)
          export MESSAGE="Create alert integration test"
          export DESCRIPTION="alert description"
          export SOURCE="create alert integration test"
          echo "ALERT_ALIAS=$(echo -n $ALIAS)" >> $GITHUB_ENV
          echo "MESSAGE=$(echo -n $MESSAGE)" >> $GITHUB_ENV
          echo "DESCRIPTION=$(echo -n $DESCRIPTION)" >> $GITHUB_ENV
          echo "SOURCE=$(echo -n $SOURCE)" >> $GITHUB_ENV

      - name: Create OpsGenie Alert
        uses: ./
        with:
          api_key: ${{ secrets.OPSGENIE_API_KEY }}
          alias: ${{ env.ALERT_ALIAS }}
          message: ${{ env.MESSAGE }}
          description: ${{ env.DESCRIPTION }}
          source: ${{ env.SOURCE }}
          priority: P5
          tags: kuku
          using_eu_url: false

      - name: Assert alert created
        env:
          OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
        run: |
          ./.github/workflows/assert_alert_created_with.js \
          ${{ env.ALERT_ALIAS }} \
          "${{ env.MESSAGE }}" \
          "${{ env.DESCRIPTION }}" \
          P5 \
          kuku \
          "${{ env.SOURCE }}"
